### ISSUE TITLE
 Настроить github actions

### ISSUE THREAD

**Issue by KayotPoziloy** [KayotPoziloy/thematic_audio_player#17]
https://docs.github.com/ru/actions
https://docs.github.com/ru/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

- [x]  CI проекта не разрешает merge PR если не прошли unit тесты #15 
- [x]  CI проекта не разрешает merge PR если unit тест coverage ниже 80%
- [x]  CI проекта не разрешает merge PR если e2e тесты не прошли #18 
- [x] СI проекта не разрешает merge PR если не прошли проверки eslint #12 #40 #36
